jwt:
  secret: "xDS21@ffe@#21"

spring:
  datasource:
    url: jdbc:h2:file:/data/desafio
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true
